version: '3.3'

services:
  identidock:
    build: . 
    ports:
      - "5000:5000"
    environment:
      ENV: DEV 
    volumes:
      - ./app:/app
    networks:
      - identidock-network

  dnmonster:
    image: amouat/dnmonster
    networks:
      - identidock-network

  redis:
    image: redis
    networks:
      - identidock-network

networks:
  identidock-network:
    external: true 
